// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FlightConnections.IT.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Feature : object, Xunit.IClassFixture<Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "01-AcoesCategorias.feature"
#line hidden
        
        public Feature(Feature.FixtureData fixtureData, FlightConnections_IT_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Features", "", "Como administrador de cadastro de rota de avião\r\nEu quero cadastrar, editar, excl" +
                    "uir e consultar rotas e vaalores\r\nPara que os usuários do sistema possam associá" +
                    "-los ao sua viagem e escolher a rota que melhor atende", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="0100 - Cadastrar rotas")]
        [Xunit.TraitAttribute("FeatureTitle", "")]
        [Xunit.TraitAttribute("Description", "0100 - Cadastrar rotas")]
        public void _0100_CadastrarRotas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("0100 - Cadastrar rotas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table1.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "10"});
                table1.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table1.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
                table1.AddRow(new string[] {
                            "4",
                            "",
                            "",
                            ""});
#line 9
 testRunner.Given("as seguintes informações para cadastro de rotas:", ((string)(null)), table1, "Dados ");
#line hidden
#line 15
 testRunner.When("cadastrar as rotas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table2.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "10"});
                table2.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table2.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 16
 testRunner.Then("devem existir as rotas cadastradas", ((string)(null)), table2, "Entao ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="0101 - Editar rotas")]
        [Xunit.TraitAttribute("FeatureTitle", "")]
        [Xunit.TraitAttribute("Description", "0101 - Editar rotas")]
        public void _0101_EditarRotas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("0101 - Editar rotas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table3.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "10"});
                table3.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table3.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 23
 testRunner.Given("as seguintes informações para edição por id:", ((string)(null)), table3, "Dados ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table4.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
#line 28
 testRunner.When("editar a rota por id", ((string)(null)), table4, "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table5.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
                table5.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table5.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 31
 testRunner.Then("devem existir todas as rotas e a editada", ((string)(null)), table5, "Entao ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="0102 - Excluir rotas")]
        [Xunit.TraitAttribute("FeatureTitle", "")]
        [Xunit.TraitAttribute("Description", "0102 - Excluir rotas")]
        public void _0102_ExcluirRotas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("0102 - Excluir rotas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table6.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "10"});
                table6.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table6.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 38
 testRunner.Given("as seguintes informações para exclusao por id:", ((string)(null)), table6, "Dados ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table7.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 43
 testRunner.When("excluir a rota por id", ((string)(null)), table7, "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table8.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "10"});
                table8.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
#line 46
 testRunner.Then("devem existir apenas os seguintes retornos", ((string)(null)), table8, "Entao ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="0103 - Consultar todas as rotas")]
        [Xunit.TraitAttribute("FeatureTitle", "")]
        [Xunit.TraitAttribute("Description", "0103 - Consultar todas as rotas")]
        public void _0103_ConsultarTodasAsRotas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("0103 - Consultar todas as rotas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table9.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
                table9.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table9.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 52
 testRunner.Given("as seguintes informações para a consulta de todas as rotas:", ((string)(null)), table9, "Dados ");
#line hidden
#line 57
 testRunner.When("consultar todas as rotas cadastradas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table10.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
                table10.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table10.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 58
 testRunner.Then("devem existir as rotas consultadas", ((string)(null)), table10, "Entao ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="0104 - Consultar rota por id")]
        [Xunit.TraitAttribute("FeatureTitle", "")]
        [Xunit.TraitAttribute("Description", "0104 - Consultar rota por id")]
        public void _0104_ConsultarRotaPorId()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("0104 - Consultar rota por id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table11.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
                table11.AddRow(new string[] {
                            "2",
                            "GRU",
                            "ORL",
                            "10"});
                table11.AddRow(new string[] {
                            "3",
                            "GRU",
                            "CDG",
                            "10"});
#line 65
 testRunner.Given("as seguintes informações para a consulta de rota por id:", ((string)(null)), table11, "Dados ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table12.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
#line 70
 testRunner.When("eu consultar rota cadastrada por id", ((string)(null)), table12, "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Origin",
                            "Destiny",
                            "Value"});
                table13.AddRow(new string[] {
                            "1",
                            "GRU",
                            "BRC",
                            "20"});
#line 73
 testRunner.Then("deve existir a rota consultada por id", ((string)(null)), table13, "Entao ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
